package com.mhv.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

import com.mhv.bean.Device;
import com.xpl.xPL_Address;

public class DeviceDAOImpl implements DeviceDAO{

	private static final String SQL_INSERT = "INSERT INTO T_DEVICE ..."; //TODO sql insert device
	
	private DAOFactory daoFactory;
	
	public DeviceDAOImpl(DAOFactory daoFactory) {
		this.daoFactory = daoFactory;
	}
	
	@Override
	public void create(Device device) throws DAOException, IllegalArgumentException {
		Connection conn = null;
		PreparedStatement preparedStatement = null;
		ResultSet autoGeneratedValues = null;
		
		try {
			/* Création du pallier en base de données */
			conn = daoFactory.getConnection();
			preparedStatement = DAOUtils.initPreparedQuery(conn, SQL_INSERT, true, null);
			int status = preparedStatement.executeUpdate();
			if(status == 0) {
				throw new DAOException("Échec de l'enregistrement du device !<br/>[sql query returned with status 0]");
			}
			autoGeneratedValues = preparedStatement.getGeneratedKeys();
			if(autoGeneratedValues.next()) {
				device.setId(autoGeneratedValues.getLong(1));
			}
			else {
				throw new DAOException("Échec de l'enregistrement du nouveau device. Aucune valeur auto-générée retournée !");
			}
			
		} catch (SQLException e) {
			throw new DAOException(e);
		}
		finally {
			DAOUtils.release(autoGeneratedValues, preparedStatement, conn);
		}
	}

	@Override
	public void deleteById(Long id) throws DAOException {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void modify(Device device) throws DAOException {
		// TODO Auto-generated method stub
		
	}

	@Override
	public List<Device> getDeviceList() throws DAOException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Device getDeviceById(Long id) throws DAOException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Device getDeviceByxPLId(xPL_Address address) throws DAOException {
		// TODO Auto-generated method stub
		return null;
	}

}
